package model;

// array of music names for lookup
public class MusicNames {
    public static final String[] NAMES = {
            "SEQ_BGM_T_05_AU", // 0x00
            "SEQ_BGM_T_05_WI", // 0x01
            "SEQ_BGM_C_01", // 0x02
            "SEQ_BGM_C_02", // 0x03
            "SEQ_BGM_C_03", // 0x04
            "SEQ_BGM_C_04", // 0x05
            "SEQ_BGM_SW_C_5_NEW", // 0x06
            "SEQ_BGM_C_06", // 0x07
            "SEQ_BGM_C_07", // 0x08
            "SEQ_BGM_C_08_B", // 0x09
            "SEQ_BGM_C_08_W", // 0x0A
            "SEQ_BGM_C_10_B", // 0x0B
            "SEQ_BGM_C_10_W", // 0x0C
            "SEQ_BGM_R_A", // 0x0D
            "SEQ_BGM_R_B_SP", // 0x0E
            "SEQ_BGM_R_B_SU", // 0x0F
            "SEQ_BGM_R_B_AU", // 0x10
            "SEQ_BGM_R_B_WI", // 0x11
            "SEQ_BGM_R_C_SP", // 0x12
            "SEQ_BGM_R_C_SU", // 0x13
            "SEQ_BGM_R_C_AU", // 0x14
            "SEQ_BGM_R_C_WI", // 0x15
            "SEQ_BGM_R_D_SP", // 0x16
            "SEQ_BGM_R_D_SU", // 0x17
            "SEQ_BGM_R_D_AU", // 0x18
            "SEQ_BGM_R_D_WI", // 0x19
            "SEQ_BGM_R_E_SP", // 0x1A
            "SEQ_BGM_R_E_SU", // 0x1B
            "SEQ_BGM_R_E_AU", // 0x1C
            "SEQ_BGM_R_E_WI", // 0x1D
            "SEQ_BGM_R_F", // 0x1E
            "SEQ_BGM_H_01", // 0x1F
            "SEQ_BGM_H_02", // 0x20
            "SEQ_BGM_H_03", // 0x21
            "SEQ_BGM_H_04", // 0x22
            "SEQ_BGM_H_05", // 0x23
            "SEQ_BGM_POKECEN", // 0x24
            "SEQ_BGM_PS", // 0x25
            "SEQ_BGM_GYM", // 0x26
            "SEQ_BGM_GROUND_GYM_01", // 0x27
            "SEQ_BGM_LABO", // 0x28
            "SEQ_BGM_GATE", // 0x29
            "SEQ_BGM_GEAR_STATION", // 0x2A
            "SEQ_BGM_BATTLE_SUBWAY", // 0x2B
            "SEQ_BGM_PALPARK", // 0x2C
            "SEQ_BGM_PLEASURE_BOAT", // 0x2D
            "SEQ_BGM_PALACE", // 0x2E
            "SEQ_BGM_UNITED_NATIONS", // 0x2F
            "SEQ_BGM_POKEMON_LEAGUE", // 0x30
            "SEQ_BGM_POKEMON_LEAGUE2", // 0x31
            "SEQ_BGM_SW_D_N_CASTLE", // 0x32
            "SEQ_BGM_D_01", // 0x33
            "SEQ_BGM_D_02", // 0x34
            "SEQ_BGM_D_03", // 0x35
            "SEQ_BGM_D_04", // 0x36
            "SEQ_BGM_D_05", // 0x37
            "SEQ_BGM_D_06", // 0x38
            "SEQ_BGM_D_CHAMPROAD", // 0x39
            "SEQ_BGM_MUGEN_lobby_B", // 0x3A
            "SEQ_BGM_MUGEN_lobby_W", // 0x3B
            "SEQ_BGM_MUGEN_D_B", // 0x3C
            "SEQ_BGM_MUGEN_D_W", // 0x3D
            "SEQ_BGM_E_TSURETEKE2", // 0x3E
            "SEQ_BGM_E_CHEREN", // 0x3F
            "SEQ_BGM_E_BERU", // 0x40
            "SEQ_BGM_E_DOCTOR", // 0x41
            "SEQ_BGM_E_DOCTOR2", // 0x42
            "SEQ_BGM_E_N_SWAN", // 0x43
            "SEQ_BGM_E_SAGE", // 0x44
            "SEQ_BGM_E_NEW_G_CIS", // 0x45
            "SEQ_BGM_E_INISHIE", // 0x46
            "SEQ_BGM_E_EMOTION", // 0x47
            "SEQ_BGM_ERECTRIC_GYM_01", // 0x48
            "SEQ_BGM_ERECTRIC_GYM_02", // 0x49
            "SEQ_BGM_INSECT_GYM_01", // 0x4A
            "SEQ_BGM_POISONE_GYM_00", // 0x4B
            "SEQ_BGM_POISONE_GYM_01", // 0x4C
            "SEQ_BGM_E_CHAMPION", // 0x4D
            "SEQ_BGM_SW_DEMO_OPENING", // 0x4E
            "SEC_BGM_E_KANRANSYA", // 0x4F
            "SEQ_BGM_SW_C_12", // 0x50
            "SEQ_BGM_SW_C_13", // 0x51
            "SEQ_BGM_SW_C_14", // 0x52
            "SEQ_BGM_MSL_FIELD", // 0x53
            "SEQ_BGM_MSL_DRESSUP", // 0x54
            "SEQ_BGM_MSL_BEFORE", // 0x55
            "SEQ_BGM_MSL_01", // 0x56
            "SEQ_BGM_MSL_02", // 0x57
            "SEQ_BGM_MSL_03", // 0x58
            "SEQ_BGM_MSL_04", // 0x59
            "SEQ_BGM_EYE_01", // 0x5A
            "SEQ_BGM_EYE_02", // 0x5B
            "SEQ_BGM_EYE_03", // 0x5C
            "SEQ_BGM_EYE_04", // 0x5D
            "SEQ_BGM_EYE_05", // 0x5E
            "SEQ_BGM_EYE_06", // 0x5F
            "SEQ_BGM_EYE_07", // 0x60
            "SEQ_BGM_EYE_08", // 0x61
            "SEQ_BGM_EYE_09", // 0x62
            "SEQ_BGM_EYE_10", // 0x63
            "SEQ_BGM_EYE_11", // 0x64
            "SEQ_BGM_EYE_12", // 0x65
            "SEQ_BGM_EYE_13", // 0x66
            "SEQ_BGM_EYE_NEO_PLASMA", // 0x67
            "SEQ_BGM_VS_NORAPOKE", // 0x68
            "SEQ_BGM_VS_TSUYOPOKE", // 0x69
            "SEQ_BGM_VS_TRAINER", // 0x6A
            "SEQ_BGM_VS_SUBWAY_TRAINER", // 0x6B
            "SEQ_BGM_VS_GYMLEADER", // 0x6C
            "SEQ_BGM_VS_RIVAL", // 0x6D
            "SEQ_BGM_VS_DPLEGEND", // 0x6E
            "SEQ_BGM_VS_SHITENNO", // 0x6F
            "SEQ_BGM_VS_CHAMP", // 0x70
            "SEQ_BGM_VS_SWAN_N", // 0x71
            "SEQ_BGM_VS_UMA", // 0x72
            "SEQ_BGM_VS_REGI", // 0x73
            "SEQ_BGM_VS_SHIN", // 0x74
            "SEQ_BGM_VS_MU", // 0x75
            "SEQ_BGM_VS_RAI", // 0x76
            "SEQ_BGM_VS_MOVEPOKE", // 0x77
            "SEQ_BGM_VS_SETPOKE", // 0x78
            "SEQ_BGM_VS_SHIRONA", // 0x79
            "SEQ_BGM_BATTLEPINCH", // 0x7A
            "SEQ_BGM_BATTLESUPERIOR", // 0x7B
            "SEQ_BGM_WIN1", // 0x7C
            "SEQ_BGM_WIN2", // 0x7D
            "SEQ_BGM_WIN3", // 0x7E
            "SEQ_BGM_WIN4", // 0x7F
            "SEQ_BGM_WIN5", // 0x80
            "SEQ_BGM_WIFLACCESS", // 0x81
            "SEQ_BGM_WIFLPRESENT", // 0x82
            "SEQ_BGM_GAME_SYNC", // 0x83
            "SEQ_BGM_GETERMINAL", // 0x84
            "SEQ_BGM_GURUGURU", // 0x85
            "SEQ_BGM_GTS", // 0x86
            "SEQ_BGM_WCS", // 0x87
            "SEQ_BGM_E_SHIRONA", // 0x88
            "SEQ_BGM_VS_TRAINER_M", // 0x89
            "SEQ_BGM_VS_TRAINER_S", // 0x8A
            "SEQ_BGM_VS_WCS", // 0x8B
            "SEQ_BGM_VS_TRAINER_WIFI", // 0x8C
            "SEQ_BGM_WIN6", // 0x8D
            "SEQ_BGM_E_LEGEND_BORN_B", // 0x8E
            "SEQ_BGM_E_LEGEND_BORN_W", // 0x8F
            "SEQ_BGM_SW_D_N_ROOM", // 0x90
            "SEQ_BGM_E_EPIROGUE", // 0x91
            "SEQ_BGM_E_EPIROGUE_W", // 0x92
            "SEQ_BGM_GF_LOGO", // 0x93
            "SEQ_BGM_MSL_DL_01", // 0x94
            "SEQ_BGM_MSL_DL_02", // 0x95
            "SEQ_BGM_MSL_DL_03", // 0x96
            "SEQ_BGM_MSL_DL_04", // 0x97
            "SEQ_BGM_SW_R_19_SP", // 0x98
            "SEQ_BGM_SW_R_19_SU", // 0x99
            "SEQ_BGM_SW_R_19_AU", // 0x9A
            "SEQ_BGM_SW_R_19_WI", // 0x9B
            "SEQ_BGM_SW_R_22_SP", // 0x9C
            "SEQ_BGM_SW_R_22_SU", // 0x9D
            "SEQ_BGM_SW_R_22_AU", // 0x9E
            "SEQ_BGM_SW_R_22_WI", // 0x9F
            "SEQ_BGM_SW_R_23", // 0xA0
            "SEQ_BGM_SW_KAZAN", // 0xA1
            "SEQ_BGM_SW_T_06", // 0xA2
            "SEQ_BGM_SW_T_07", // 0xA3
            "SEQ_BGM_SW_D_22", // 0xA4
            "SEQ_BGM_SW_D_23", // 0xA5
            "SEQ_BGM_SW_D_GESU", // 0xA6
            "SEQ_BGM_SW_D_24_W", // 0xA7
            "SEQ_BGM_SW_D_24_B", // 0xA8
            "SEQ_BGM_SW_D_25", // 0xA9
            "SEQ_BGM_SW_D_27_F_AJITO", // 0xAA
            "SEQ_BGM_SW_D_27_L_AJITO", // 0xAB
            "SEQ_BGM_SW_D_27_G_AJITO", // 0xAC
            "SEQ_BGM_SW_D_REGI", // 0xAD
            "SEQ_BGM_SW_D_UMA", // 0xAE
            "SEQ_BGM_SW_H_06", // 0xAF
            "SEQ_BGM_WBTLOBBY", // 0xB0
            "SEQ_BGM_WBT_GROUND", // 0xB1
            "SEQ_BGM_WBT_FANFARE", // 0xB2
            "SEQ_BGM_PW_LAND", // 0xB3
            "SEQ_BGM_PW_FILMING", // 0xB4
            "SEQ_BGM_PW_SCENARIO_01_F", // 0xB5
            "SEQ_BGM_PW_SCENARIO_01_L", // 0xB6
            "SEQ_BGM_PW_SCENARIO_02_F", // 0xB7
            "SEQ_BGM_PW_SCENARIO_02_L", // 0xB8
            "SEQ_BGM_PW_SCENARIO_03_F", // 0xB9
            "SEQ_BGM_PW_SCENARIO_03_L", // 0xBA
            "SEQ_BGM_PW_SCENARIO_04_F", // 0xBB
            "SEQ_BGM_PW_SCENARIO_04_L", // 0xBC
            "SEQ_BGM_PW_SCENARIO_05_F", // 0xBD
            "SEQ_BGM_PW_SCENARIO_05_L", // 0xBE
            "SEQ_BGM_PW_SCENARIO_06_F", // 0xBF
            "SEQ_BGM_PW_SCENARIO_06_L", // 0xC0
            "SEQ_BGM_PW_SCENARIO_07_F", // 0xC1
            "SEQ_BGM_PW_SCENARIO_07_L", // 0xC2
            "SEQ_BGM_PW_SCENARIO_08_F", // 0xC3
            "SEQ_BGM_FLIGHT_GYM_01", // 0xC4
            "SEQ_BGM_WATER_GYM_01", // 0xC5
            "SEQ_BGM_DRAGON_GYM_01", // 0xC6
            "SEQ_BGM_LCG_01", // 0xC7
            "SEQ_BGM_LCG_02", // 0xC8
            "SEQ_BGM_DATA_CONV", // 0xC9
            "SEQ_BGM_REZO_RIZO", // 0xCA
            "SEQ_BGM_FES", // 0xCB
            "SEQ_BGM_SW_DEMO_SHIP", // 0xCC
            "SEQ_BGM_SW_DEMO_FLIGHT", // 0xCD
            "SEQ_BGM_SW_DEMO_UNION_00", // 0xCE
            "SEQ_BGM_SW_DEMO_UNION_01", // 0xCF
            "SEQ_BGM_SW_DEMO_UNION_02", // 0xD0
            "SEQ_BGM_SW_DEMO_UNION_03B", // 0xD1
            "SEQ_BGM_SW_DEMO_UNION_03W", // 0xD2
            "SEQ_BGM_SW_DEMO_AJITO_SHIP", // 0xD3
            "SEQ_BGM_SW_DEMO_FRIGATE", // 0xD4
            "SEQ_BGM_E_HUE", // 0xD5
            "SEQ_BGM_E_ACHROMA", // 0xD6
            "SEQ_BGM_DARK_TRINITY", // 0xD7
            "SEQ_BGM_E_7_SAGE", // 0xD8
            "SEQ_BGM_E_C08_ICE", // 0xD9
            "SEQ_BGM_E_EPILOGUE", // 0xDA
            "SEQ_BGM_EYE_DANCER", // 0xDB
            "SEQ_BGM_EYE_CLOWN", // 0xDC
            "SEQ_BGM_VS_RG_LEADER", // 0xDD
            "SEQ_BGM_VS_RG_CHAMP", // 0xDE
            "SEQ_BGM_VS_GS_LEADER", // 0xDF
            "SEQ_BGM_VS_GS_CHAMP", // 0xE0
            "SEQ_BGM_VS_RG_LEADER", // 0xE1
            "SEQ_BGM_VS_RG_CHAMP", // 0xE2
            "SEQ_BGM_VS_DP_LEADER", // 0xE3
            "SEQ_BGM_VS_DP_CHAMP", // 0xE4
            "SEQ_BGM_VS_BW_CHAMP", // 0xE5
            "SEQ_BGM_VS_WBT", // 0xE6
            "SEQ_BGM_VS_KYURAMU", // 0xE7
            "SEQ_BGM_VS_KYUROMU", // 0xE8
            "SEQ_BGM_VS_NEO_PLASMA", // 0xE9
            "SEQ_BGM_VS_ACHROMA", // 0xEA
            "SEQ_BGM_VS_NEW_G_CIS", // 0xEB
            "SEQ_BGM_VS_IRIS", // 0xEC
            "SEQ_BGM_VS_BANJIROU", // 0xED
            "SEQ_BGM_VS_HUE", // 0xEE
            "SEQ_BGM_WIN_WBT", // 0xEF
            "SEQ_BGM_KEMONOMICHI", // 0xF0
            "SEQ_BGM_JAPARADE", // 0xF1
            "SEQ_BGM_E_PLASMA", // 0xF2
            "SEQ_BGM_VS_ELITE_PLASMA", // 0xF3
            "SEQ_BGM_THEEND", // 0xF4
            "SEQ_BGM_EV_GIANTHOLE_01", // 0xF5
            "SEQ_BGM_EV_GIANTHOLE_02", // 0xF6
            "SEQ_BGM_EV_GIANTHOLE_03", // 0xF7
            "SEQ_BGM_END" // 0xF8
    };

    private MusicNames() {
    }

    public static String musicNameForCode(int code) {
        if (code < 0 || code >= NAMES.length)
            return "null";
        String n = NAMES[code];
        return n;
    }
}
